Move SSLContext to own function, also pass it to plain TLS connections
poezio/slixmpp pull request #8
Opened 2017-05-05 15:04 UTC by mathiasertl

This pull request moves getting the SSL context used for STARTLS into its own function. It also passes the context to plain TLS connections (now becoming more important again due to [XEP-0368](https://xmpp.org/extensions/xep-0368.html) instead of just passing True/False.

The motivation for this change is that I want to use the library for testing supported TLS ciphers like what xmpp.net used to do. 

For that I built build a custom client where I can override the `get_ssl_context` method and return a very specific Context so I know exactly what I'm testing.

2017-05-16 15:18 UTC, louiz commented
Thank you for your contribution (and sorry for the silence during more than 10 days…).

This looks fine. Maybe just change your False into None. Because when it’s False, I assume the only other valid value is True, instead of a context object.

2017-05-16 15:19 UTC, louiz requested changes

2017-05-16 15:19 UTC, louiz commented on slixmpp/xmlstream/xmlstream.py
> +
Is there a reason why it’s False instead of None?

2017-05-24 11:19 UTC, louiz commented
Merged

2017-05-24 11:19 UTC, closed without merging

2017-05-29 16:24 UTC, mathiasertl commented
@louiz sorry from my side for not answering sooner, I was on (much needed) vacation.

I see you already merged this, but I'd like to explain my rationale for `False` vs. `None` anyway. The documentation [states](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.AbstractEventLoop.create_connection):

> ssl: if given and not false, a SSL/TLS transport is created (by default a plain TCP transport is created). If ssl is a ssl.SSLContext object, this context is used to create the transport; if ssl is True, a context with some unspecified default settings is used.

Strictly speaking (although it would be a common ambiguity in the python docs), this means that `None` is the default value for the parameter (= No TLS), but actually passing `None` should create a TLS context (since passing `None` matches "if given and not false"). Then again the lower-case `false` means you could argue it is "any falsy value". But in any case, `False` seems more explicit to what you want (-> no TLS) in that specific branch.